symfony-cmf/routing-bundle

.travis.yml

Due to a bug in Composer, caching the vendor directory won't work very nice. (if `master` is aliased as `1.3-dev`, it'll cache the branch name instead of the alias, so it'll install the `master` branch, even if the alias changed to `2.0-dev`).

Cache the deps instead of the vendor directory

---

DependencyInjection/CmfRoutingExtension.php
Resources/config/provider-orm.xml

|Q|A|
|---|---|
|Bug fix?|yes
|New feature?|yes
|BC breaks?|no
|Deprecations?|no
|Tests pass?|?
|Fixed tickets|	
|License|MIT
|Doc PR|not yet
ORM content repository implementation was already included in the bundle, 
but not well declared in provider-orm.xml,
nor loaded in the extension.

ORM content repository implementation ready

---

Admin/RouteAdmin.php
Resources/config/admin-phpcr.xml

removing the setControllerResolver method leads to problems when a service definition tries to call this method.
/cc @EmmanuelVella

revert BC break introduced in #292

---

Doctrine/Phpcr/PrefixCandidates.php
Tests/Unit/Doctrine/Phpcr/PrefixCandidatesTest.php

Symfony\Component\Routing\Matcher\UrlMatcher::match() performs a rawurldecode() on a request's pathInfo in order to find matching routes, so one must do the same when generating candidate routes.

Generate candidates from decoded URLs

---

.travis.yml
Admin/Extension/FrontendLinkExtension.php
Tests/WebTest/RedirectRouteAdminTest.php
composer.json

Let's see how this turns out.
I've also removed some unsupported versions and made sure the main tests are against the latest stable versions (sf 2.6 and PHP 5.6)

Test lowest versions of dependencies

---

Admin/RouteAdmin.php

when locale pattern is activated, add a field for the locale, not for the format

fix bug in sonata admin

---

CHANGELOG.md
DependencyInjection/CmfRoutingExtension.php
DependencyInjection/Configuration.php
Tests/Unit/DependencyInjection/CmfRoutingExtensionTest.php
Tests/Unit/DependencyInjection/ConfigurationTest.php
UPGRADE-1.3.md

| Deprecations? | yes
| Fixed tickets | https://github.com/symfony-cmf/RoutingBundle/issues/290
| Doc PR        | https://github.com/symfony-cmf/symfony-cmf-docs/pull/715
* Deprecated the `route_basepath` setting in favor of `route_basepaths`
* Allowed string values for `route_basepaths`, in case only one basepath needs to be configured
* Configuring `route_basepaths` overrides the default `/cms/routes` value, add it explicitely to include it in the basepath list
* Multiple `route_basepaths` configuration in multiple config files results in merging all configured basepaths.
* Make sure no duplicated basepaths are configured
* Improve testing
/cc @dbu

Fix route basepaths configuration

---

Doctrine/Phpcr/RedirectRoute.php
Doctrine/Phpcr/Route.php
Tests/Functional/Doctrine/Phpcr/RouteProviderTest.php
Tests/Resources/DataFixtures/Phpcr/LoadRouteData.php

Symfony does now have really nice tools and a good handling of deprecation notices. So we should trigger deprecation notices whenever we deprecate anything.
Besides that, this 1.x release is probably one of the last releases in the 1 major so it also makes sense to warn users about deprecated features.
/cc @lsmith77 @dbu @dantleech

Trigger deprecation notices

---

DependencyInjection/CmfRoutingExtension.php
DependencyInjection/Configuration.php
Resources/config/provider-orm.xml
Resources/config/provider-phpcr.xml
Tests/Resources/Fixtures/config/config.xml

Reasoning
---
The DI extension was very big and hard to follow. It's still pretty big, but I tried to simplify it a bit by moving some validation to the Configuration and splitting the handling in some methods.
Changes included in this PR
---
* Made all methods in the extension class private instead of public (except from `load()`). These methods shouldn't be overriden and I don't think this is a BC break as nobody will ever override a DI extension (or they must do something very hacky).
* Changed all `$this->getAlias()` calls to just `"cmf_routing"`. I don't see any advantage of calling this method: The `cmf_routing` prefix is already hardcoded in the service configuration files and many other places. To me, it only adds many method calls and some confusion (especially when used inside a …

Clean up DI Extension & Configuration classes

---

.travis.yml
DependencyInjection/CmfRoutingExtension.php
DependencyInjection/Configuration.php
Resources/config/initializer-phpcr.xml
Tests/Unit/DependencyInjection/CmfRoutingExtensionTest.php

Related PR Sylius/Sylius#3668.

Made PHPCR initializer independent, creating all route_basepaths

---

.travis.yml
Admin/Extension/RouteReferrersExtension.php
Admin/RedirectRouteAdmin.php
Admin/RouteAdmin.php
Controller/RedirectController.php
Form/Type/RouteTypeType.php
Tests/Functional/Routing/DynamicRouterTest.php
Util/Sf2CompatUtil.php
composer.json

Symfony 2.8 support

---

CHANGELOG.md
Resources/config/doctrine-model/Route.orm.xml
Resources/config/doctrine-orm/Route.orm.xml

hardcode column names that are used in index definitions to not fail on non-default naming strategies.
as far as i can tell, this should be no BC break, as non-default naming strategies previously must have lead to an error as described in #309. if the user overwrote the mapping, they will not see the change we do here.
fix #309

do not fail on non-default naming strategies

---

.travis.yml
Admin/RedirectRouteAdmin.php
Admin/RouteAdmin.php
Model/Route.php
Tests/Resources/app/config/cmf_routing.phpcr.yml
Tests/Unit/Routing/DynamicRouterTest.php
Tests/WebTest/RedirectRouteAdminTest.php
Tests/WebTest/RouteAdminTest.php
composer.json

- allow Symfony ~3.0
- bump Symfony dependency to ~2.7
- specify correct Sonata dependencies
- use parentDocument in Admin classes
- update route_basepaths in tests
- make StyleCI happy
See #331

Symfony3 compatibility

---

DependencyInjection/CmfRoutingExtension.php
Resources/config/routing-dynamic.xml
Tests/Unit/DependencyInjection/CmfRoutingExtensionTest.php

| Bug fix?      | [no]
| Fixed tickets | []
| Doc PR        | []
use docs [Writing your own Route Enhancers](http://symfony.com/doc/master/cmf/bundles/routing/dynamic_customize.html#writing-your-own-route-enhancers) for the create internal Enhancers, I think it's more clearer.
what do you think?

use tag dynamic_router_route_enhancer for the all enhancer

---

.travis.yml
Admin/Extension/FrontendLinkExtension.php

When using SonataTranslationBundle, if we edit the `de` content, I want to go to the de content when clicking the "front-end link" button. However, at the moment, the locale of the admin panel is used instead of the edited content. This PR changes/fixes that

Use content locale for frontend link

---

Doctrine/RouteConditionMetadataListener.php

Sometimes, Metadata ReflectionClass is null and throws:
PHP Fatal error:  Call to a member function getName() on a non-object in vendor/symfony-cmf/routing-bundle/Doctrine/RouteConditionMetadataListener.php on line 52
i.e. I get this error when I try to use doctrine:generate:entities command using orm persistence.

Check Metadata Class info exists

---

composer.json

since removing the getParent method from the Route document, we conflict with phpcr-odm 1.* that had this in its interface

declare conflict with phpcr-odm 1.*

---

Tests/Unit/Doctrine/Phpcr/ContentRepositoryTest.php
Tests/Unit/Doctrine/Phpcr/RouteTest.php
Tests/Unit/Form/Type/RouteTypeTypeTest.php

Fixed typo in extends usage of PHPUnit_Framework_TestCase in 3 tests

---

CHANGELOG.md
CmfRoutingBundle.php
DependencyInjection/CmfRoutingExtension.php
DependencyInjection/Configuration.php
Resources/config/provider-orm.xml
Tests/Unit/DependencyInjection/CmfRoutingExtensionTest.php
Tests/Unit/DependencyInjection/ConfigurationTest.php

| Doc PR        | [symfony-cmf/symfony-cmf-docs#779](https://github.com/symfony-cmf/symfony-cmf-docs/pull/779)
As PHPCR easily allows you to add custom properties (and own class) to Route, this functionality ix missing in ORM implementation. This PR replaces hardcoded Route class name with configuration parameter and register doctrine mapping config pass for only needed directories. 
In case of custom Route class all what you need to do is adding `route_class` to orm config:
```
cmf_routing:
...
dynamic:
persistence:
orm:
enabled: true
route_class: "SWP\\Bundle\\ContentBundle\\Doctrine\\ORM\\Route"
```

Add option to use custom Route class in ORM

---

src/Doctrine/RouteConditionMetadataListener.php

Hi,
In my Symfony (3.2) project, when I run doctrine:generate:entities, on every Entity of my application there appears a new column $condition. This happened since I upgraded this bundle to 1.4 (back on Symfony 2.8), the problem remains when upgrading Symfony to 3.2, and I also updated this bundle to 2.0.
This seems to occur in `src/Doctrine/RouteConditionMetadataListener.php::loadClassMetadata`. I tried to debug this, and when my Entities go through this loop, the $refl variable is being set to `null`, which allows them to continue, and append a new $condition column, which seems wrong.
Can anybody check if this change would break the expected behaviour (tests pass), and if this change correctly fixes the issue. 
| New …

Fix an issue where $condition columns are mapped on every entity during doctrine:generate:entities 

---

.travis.yml
CHANGELOG.md
composer.json
src/Doctrine/Phpcr/RedirectRoute.php
src/Doctrine/Phpcr/Route.php

| Deprecations? | yes
as discussed on slack, lets keep support for phpcr-odm 1.4 so we can release without needing phpcr-odm 2.0 first.

Keep support for PHPCR-ODM 1.4

---

CHANGELOG.md
UPGRADE-2.0.md
composer.json
src/DependencyInjection/CmfRoutingExtension.php
src/DependencyInjection/Configuration.php
src/Resources/config/schema/routing-1.0.xsd
tests/Resources/Fixtures/config/config.php
tests/Resources/Fixtures/config/config.xml
tests/Resources/Fixtures/config/config.yml
tests/Resources/Fixtures/config/config3.xml
tests/Unit/DependencyInjection/ConfigurationTest.php

this configuration is only used in the sonata admin
| Bug fix?      | [yes]
| BC breaks?    | [yes]
| Doc PR        | https://github.com/symfony-cmf/symfony-cmf-docs/pull/814

remove unused content_basepath from phpcr configuration

---

CHANGELOG.md
UPGRADE-2.0.md
src/Routing/DynamicRouter.php

$template is in line with the FrameworkBundle TemplateController
| BC breaks?    | yes
| Tests pass?   | travis-ci
| Doc PR        | TODO
together with https://github.com/symfony-cmf/content-bundle/pull/174

do not rename the template in dynamic router

---

CHANGELOG.md
src/Resources/config/routing-dynamic.xml
src/Routing/DynamicRouter.php
tests/Unit/Routing/DynamicRouterTest.php

defaults to false in 2.8 and triggers deprecation since symfony 3.3
| Tests pass?   | see travis
related to https://github.com/symfony/symfony/pull/21662

use request stack rather than a single request

---

CHANGELOG.md
composer.json
src/CmfRoutingBundle.php
src/DependencyInjection/Compiler/TemplatingValidatorPass.php
src/Doctrine/Phpcr/ContentRepository.php
src/Doctrine/Phpcr/IdPrefixListener.php
src/Resources/config/validators.xml
src/Validator/Constraints/RouteDefaultsTemplatingValidator.php
src/Validator/Constraints/RouteDefaultsTwigValidator.php
tests/Unit/Validator/Constraints/RouteDefaultsTemplatingValidatorTest.php
tests/Unit/Validator/Constraints/RouteDefaultsTwigValidatorTest.php
tests/Unit/Validator/Constraints/RouteDefaultsValidatorTest.php

| Bug fix?      | [no]
| Fixed tickets | [#396]
fix #396 
I  replaced templating by a twig loader based on the comment of @fabpot (maybe you can give us a internal in review)
https://github.com/symfony/recipes-contrib/pull/91#issuecomment-331666757
@dbu @wouterj I have no clue if we can release that on a patch release or if it is an BC-Break. From my POV we didn't change any external API, so a patch release would be ok.

use twig loader to validate template's existence

---

src/DependencyInjection/Compiler/TemplatingValidatorPass.php

I unfortunately did an error. The interface check was done by `::class` and so the use statement broke the app where i required the new release.

use a string for the interface check

---

src/DependencyInjection/Compiler/TemplatingValidatorPass.php

remove interface check at all

---

src/DependencyInjection/Compiler/SetRouterPass.php

Services are private by default since Symfony 3.4. Since the router service is still directly accesses in various places it needs to be explicitly marked as `public` to prevent deprecations in Symfony 3.4 and errors in Symfony 4.0.
| Branch?       | "master"

Fix access of private router service since Symfony 3.4

---

src/Form/Type/RouteTypeType.php
tests/Functional/Doctrine/Phpcr/RouteProviderTest.php
tests/Functional/Routing/DynamicRouterTest.php
tests/Unit/DependencyInjection/XmlSchemaTest.php
tests/Unit/Doctrine/Orm/ContentRepositoryTest.php
tests/Unit/Doctrine/Phpcr/ContentRepositoryTest.php
tests/Unit/Doctrine/Phpcr/RouteProviderTest.php
tests/Unit/Doctrine/Phpcr/RouteTest.php
tests/Unit/Routing/DynamicRouterTest.php
tests/Unit/Validator/Constraints/RouteDefaultsValidatorTest.php

| Branch?       | master
| Deprecations? |no
| Fixed tickets | n/a
| Doc PR        | n/a
This PR updates the tests by removing the usage of the deprecated `each` function.

Removed usage of the deprecated `each` function

---

src/DependencyInjection/Compiler/ValidationPass.php

This validation is done only when the Symfony validator builder is available.
| Branch?       | master
| Fixed tickets | #413
| Doc PR        | n/a

Fixed #413: Made PHPCR documents validation optional

---

tests/Unit/DependencyInjection/Compiler/TemplatingValidatorPassTest.php
tests/Unit/DependencyInjection/Compiler/ValidationPassTest.php

| Branch?       | master
| Fixed tickets | #415 
| Doc PR        | n/a
This PR adds unit tests for the _ValidationPass_ and the _TemplatingValidationPass_ compiler passes.

Add compiler passes unit tests

---

composer.json

I realized in https://github.com/symfony-cmf/symfony-cmf/pull/258 that `symfony/twig-bundle` isn't the correct choice. So i try `twig/twig`

use twig/twig instead of symfony/twig-bundle

---

src/Doctrine/Phpcr/RouteProvider.php

As it turns out, the pipe character also causes Jackrabbit errors.
| Branch?       | "master"
| Deprecations? | /no
| Fixed tickets | #430
| Doc PR        | reference to the documentation PR, if any

Add another invalid character

---

src/DependencyInjection/Configuration.php

`The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "cmf_routing" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.`
| Deprecations? | yes
| Doc PR        |

fix symfony 4.3 deprecation about root nodes

---

composer.json
src/CmfRoutingBundle.php
src/Doctrine/DoctrineProvider.php
src/Doctrine/Orm/RouteProvider.php
src/Doctrine/Phpcr/IdPrefixListener.php
src/Doctrine/Phpcr/LocaleListener.php
src/Doctrine/Phpcr/PrefixCandidates.php
src/Doctrine/Phpcr/RouteProvider.php
src/Doctrine/RouteConditionMetadataListener.php
tests/Fixtures/App/DataFixtures/Phpcr/LoadRouteData.php
tests/Unit/Doctrine/Orm/ContentRepositoryTest.php
tests/Unit/Doctrine/Orm/RouteProviderTest.php
tests/Unit/Doctrine/Phpcr/ContentRepositoryTest.php
tests/Unit/Doctrine/Phpcr/IdPrefixListenerTest.php
tests/Unit/Doctrine/Phpcr/LocaleListenerTest.php
tests/Unit/Doctrine/Phpcr/PrefixCandidatesTest.php
tests/Unit/Doctrine/Phpcr/RouteProviderTest.php
tests/Unit/Form/Type/RouteTypeTypeTest.php

mark conflict with too old doctrine common versions
| Fixed tickets | #452 

adjust to doctrine commons split out persistence

---

.github/workflows/test-application.yaml
composer.json
src/Controller/RedirectController.php
tests/Functional/Routing/DynamicRouterTest.php

| Branch?       | "master"
| Doc PR        | 
Passing objects as the route name is deprecated in `symfony-cmf/routing`, so I refactored this controller that there are no deprecations triggered.
The 2 fixes in the github workflow are needed to make the tests pass (the failures are unrelated to this change)

Avoid using deprecated feature from symfony-cmf/routing library
