.travis.yml, Tests/WebTest/RedirectRouteAdminTest.php, Tests/WebTest/RouteAdminTest.php
Let's see how this turns out :)
=> Test against PHP7

Doctrine/Orm/RouteProvider.php, Doctrine/Phpcr/RouteProvider.php
=> avoid exception on cache warmup when database does not exist yet.

.github/PULL_REQUEST_TEMPLATE.md
| Bug fix?      | [no]
| Fixed tickets | []
| Doc PR        | []
See https://github.com/blog/2111-issue-and-pull-request-templates
=> create pull request template

Doctrine/Orm/ContentRepository.php
| Bug fix?      | [yes]
| Fixed tickets | []
| Doc PR        | []
=> [orm][bug] fix create contentId by Object

Model/Route.php
| Bug fix?      | [no]
| Fixed tickets | []
| Doc PR        | []
fix code style https://styleci.io/analyses/qgOEDQ
=> fix cs styleci.io

DependencyInjection/CmfRoutingExtension.php, Resources/config/routing-dynamic.xml, Tests/Unit/DependencyInjection/CmfRoutingExtensionTest.php, composer.json
| Fixed tickets | https://github.com/symfony-cmf/RoutingBundle/issues/337
=> init content repository enhancer

Doctrine/Phpcr/RedirectRoute.php, Doctrine/Phpcr/Route.php, Model/Route.php
=> fix broken style check

CHANGELOG.md, Resources/config/admin-phpcr.xml, Resources/config/form-type.xml, Resources/config/provider-orm.xml, Resources/config/provider-phpcr.xml, Resources/config/routing-chain.xml, Resources/config/routing-dynamic.xml, Resources/config/validators.xml
=> Removed *.class parameters

DependencyInjection/Compiler/ValidationPass.php
=> fixing path to validation file

UPGRADE-2.0.md
=> mention admin changes

composer.json, src/CmfRoutingBundle.php
=> we don't need the mapping pass from core bundle anymore

composer.json
=> Cleanup deps

composer.json
| Bug fix?      | [yes|no]
| New feature?  | [yes|no]
| BC breaks?    | [yes|no]
| Deprecations? | [yes|no]
| Tests pass?   | [yes|no]
| Fixed tickets | [comma-separated list of tickets fixed by the PR, if any]
| Doc PR        | [reference to the documentation PR, if any]
=> increase next dev version

src/DependencyInjection/Compiler/TemplatingValidatorPass.php, tests/Functional/Doctrine/Phpcr/RouteProviderTest.php
@stof had a hint in the PR, where we introduced it.
=> Fix reference

.travis.yml, README.md, composer.json, tests/Unit/Validator/Constraints/RouteDefaultsValidatorTest.php
=> Allow Symfony 4.0

.travis.yml, Makefile
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | yes/no
| Deprecations? | yes/no
| Fixed tickets | comma-separated list of tickets fixed by the PR, if any
| Doc PR        | reference to the documentation PR, if any
=> DevKit updates - Remove dev 

src/Resources/config/routing-dynamic.xml
| Fixed tickets | https://github.com/symfony-cmf/routing-bundle/issues/425
=> Make redirect controller service public

README.md
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | yes/no
| Deprecations? | yes/no
| Fixed tickets | comma-separated list of tickets fixed by the PR, if any
| Doc PR        | reference to the documentation PR, if any
=> DevKit updates

src/Form/Type/RouteTypeType.php, tests/Unit/Form/Type/RouteTypeTypeTest.php
=> Fix use label as key in type choice array

src/Doctrine/Phpcr/PrefixCandidates.php, src/Doctrine/Phpcr/RouteProvider.php
| Branch?       | "master" 
| Fixed tickets | #430
| Doc PR        | none
Fixes #430
=> Fix for invalid Jackrabbit characters in URLs

.styleci.yml, .travis.yml, Makefile, composer.json, src/Doctrine/Phpcr/Route.php, tests/Fixtures/App/config/config.yml, tests/Functional/Doctrine/Orm/OrmTestCase.php, tests/Unit/DependencyInjection/Compiler/TemplatingValidatorPassTest.php, tests/Unit/Validator/Constraints/RouteDefaultsTemplatingValidatorTest.php
hopefully this will fix the build.
=> clean up build matrix

CHANGELOG.md, src/Resources/config/routing-chain.xml
fix #442
continuation with the changes of master branch to see if there are any build failures
=> Autowiring

CHANGELOG.md, composer.json
allow installation with twig 3
=> allow twig 3

.gitignore, .travis.yml, CHANGELOG.md, composer.json, tests/Fixtures/App/config/config.yml, tests/Functional/Controller/RedirectControllerTest.php, tests/Functional/Doctrine/Orm/RedirectRouteTest.php, tests/Functional/Doctrine/Orm/RouteProviderTest.php, tests/Functional/Doctrine/Phpcr/RedirectRouteTest.php, tests/Functional/Doctrine/Phpcr/RouteProviderTest.php, tests/Functional/Doctrine/Phpcr/RouteTest.php, tests/Functional/Routing/DynamicRouterTest.php, tests/Unit/DependencyInjection/CmfRoutingExtensionTest.php, tests/Unit/DependencyInjection/Compiler/SetRouterPassTest.php, tests/Unit/DependencyInjection/Compiler/TemplatingValidatorPassTest.php, tests/Unit/DependencyInjection/Compiler/ValidationPassTest.php, tests/Unit/DependencyInjection/ConfigurationTest.php, tests/Unit/DependencyInjection/XmlSchemaTest.php, tests/Unit/Doctrine/Orm/ContentRepositoryTest.php, tests/Unit/Doctrine/Orm/RouteProviderTest.php, tests/Unit/Doctrine/Phpcr/ContentRepositoryTest.php, tests/Unit/Doctrine/Phpcr/IdPrefixListenerTest.php, tests/Unit/Doctrine/Phpcr/LocaleListenerTest.php, tests/Unit/Doctrine/Phpcr/RouteProviderTest.php, tests/Unit/Doctrine/Phpcr/RouteTest.php, tests/Unit/Form/Type/RouteTypeTypeTest.php, tests/Unit/Routing/DynamicRouterTest.php, tests/Unit/Validator/Constraints/RouteDefaultsTemplatingValidatorTest.php, tests/Unit/Validator/Constraints/RouteDefaultsValidatorTest.php
blocked by https://github.com/symfony-cmf/Routing/pull/240
=> build with symfony 5

.travis.yml, composer.json
| Branch?       | master
| Fixed tickets | #456
| Doc PR        |
=> PHP 8.0 Compatibility

CHANGELOG.md, src/Resources/config/doctrine-orm/Route.orm.xml
| Branch?       | 2.5.1
| New feature?  |no
| Doc PR        | 
[Old PR](https://github.com/symfony-cmf/routing-bundle/pull/467)
=> Correct create index for ORM
